package zzuegg.ecs.system;

import zzuegg.ecs.change.ChangeTracker;
import zzuegg.ecs.component.ComponentId;
import zzuegg.ecs.component.Mut;
import zzuegg.ecs.storage.Chunk;
import zzuegg.ecs.storage.ComponentStorage;

import java.lang.classfile.*;
import java.lang.classfile.attribute.SourceFileAttribute;
import java.lang.constant.*;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Generates ChunkProcessor implementations at runtime using the ClassFile API.
 * The generated class contains a direct invokevirtual to the system method,
 * eliminating MethodHandle dispatch overhead entirely.
 */
public final class ChunkProcessorGenerator {

    private static final AtomicInteger COUNTER = new AtomicInteger(0);

    private ChunkProcessorGenerator() {}

    public static ChunkProcessor generate(SystemDescriptor desc, Object[] serviceArgs) {
        return generate(desc, serviceArgs, true);
    }

    public static ChunkProcessor generate(SystemDescriptor desc, Object[] serviceArgs,
                                          boolean useDefaultStorageFactory) {
        var accesses = desc.componentAccesses();
        var method = desc.method();
        var instance = desc.instance();
        var params = method.getParameters();
        int paramCount = params.length;

        // Pre-compute param info
        boolean[] isRead = new boolean[paramCount];
        boolean[] isWrite = new boolean[paramCount];
        boolean[] isEntity = new boolean[paramCount];
        boolean[] isValueTracked = new boolean[paramCount];
        ComponentId[] compIds = new ComponentId[paramCount];
        int compIdx = 0;

        for (int i = 0; i < paramCount; i++) {
            if (params[i].isAnnotationPresent(Read.class)) {
                isRead[i] = true;
                compIds[i] = accesses.get(compIdx++).componentId();
            } else if (params[i].isAnnotationPresent(Write.class)) {
                isWrite[i] = true;
                compIds[i] = accesses.get(compIdx++).componentId();
            } else if (desc.entityParamSlots().contains(i)) {
                isEntity[i] = true;
            }
        }

        // Tier 1: Maximally optimized generator. Uses direct array access if
        // the world is known to use the default storage factory; otherwise
        // falls back to interface-based dispatch (still tier-1 but slower).
        var generatedProcessor = GeneratedChunkProcessor.tryGenerate(desc, serviceArgs, useDefaultStorageFactory);
        if (generatedProcessor != null) {
            return generatedProcessor;
        }

        // Tier 2: invokeExact with arity specialization (1-4 params, handles writes)
        var bytecodeProcessor = BytecodeChunkProcessor.tryGenerate(desc, serviceArgs);
        if (bytecodeProcessor != null) {
            return bytecodeProcessor;
        }

        // Fallback: optimized concrete class
        return new DirectProcessor(
            desc, instance, paramCount, isRead, isWrite, isEntity, isValueTracked,
            compIds, serviceArgs
        );
    }

    /**
     * Concrete processor class — not generated bytecode, but structured to give
     * the JIT maximum optimization opportunity:
     * - All fields are final
     * - Single concrete class (monomorphic dispatch)
     * - No virtual calls in the hot loop except ComponentStorage.get/set
     * - Args array and Mut instances are pre-allocated and reused
     */
    static final class DirectProcessor implements ChunkProcessor {

        private final Object instance;
        private final SystemInvoker invoker;
        private final int paramCount;
        private final boolean[] isRead;
        private final boolean[] isWrite;
        private final boolean[] isEntity;
        private final boolean[] isValueTracked;
        private final ComponentId[] compIds;
        private final Object[] args;
        @SuppressWarnings("rawtypes")
        private final Mut[] muts;
        private final boolean anyEntity;

        DirectProcessor(SystemDescriptor desc, Object instance, int paramCount,
                        boolean[] isRead, boolean[] isWrite, boolean[] isEntity,
                        boolean[] isValueTracked,
                        ComponentId[] compIds, Object[] serviceArgs) {
            this.instance = instance;
            this.invoker = SystemInvoker.create(desc);
            this.paramCount = paramCount;
            this.isRead = isRead;
            this.isWrite = isWrite;
            this.isEntity = isEntity;
            this.isValueTracked = isValueTracked;
            this.compIds = compIds;
            this.args = new Object[paramCount];
            this.muts = new Mut[paramCount];
            boolean anyEnt = false;
            for (boolean e : isEntity) if (e) { anyEnt = true; break; }
            this.anyEntity = anyEnt;

            // Pre-fill service args (non-component, non-entity params stay
            // constant across the whole run).
            for (int i = 0; i < paramCount; i++) {
                if (!isRead[i] && !isWrite[i] && !isEntity[i]) {
                    args[i] = serviceArgs[i];
                }
            }
        }

        @Override
        @SuppressWarnings({"unchecked", "rawtypes"})
        public void process(Chunk chunk, long currentTick) {
            var storages = new ComponentStorage[paramCount];
            var trackers = new ChangeTracker[paramCount];
            for (int i = 0; i < paramCount; i++) {
                if (isRead[i] || isWrite[i]) {
                    storages[i] = chunk.componentStorage(compIds[i]);
                    if (isWrite[i]) {
                        trackers[i] = chunk.changeTracker(compIds[i]);
                    }
                }
            }

            int count = chunk.count();
            var localArgs = this.args;
            var localMuts = this.muts;
            var localStorages = storages;

            for (int slot = 0; slot < count; slot++) {
                zzuegg.ecs.entity.Entity currentEntity = anyEntity ? chunk.entity(slot) : null;
                for (int i = 0; i < paramCount; i++) {
                    if (isRead[i]) {
                        localArgs[i] = localStorages[i].get(slot);
                    } else if (isWrite[i]) {
                        var m = localMuts[i];
                        if (m == null) {
                            m = new Mut(localStorages[i].get(slot), slot, trackers[i], currentTick, isValueTracked[i]);
                            localMuts[i] = m;
                            localArgs[i] = m;
                        } else {
                            m.reset(localStorages[i].get(slot), slot, trackers[i], currentTick);
                        }
                    } else if (isEntity[i]) {
                        localArgs[i] = currentEntity;
                    }
                }

                try {
                    invoker.invoke(localArgs);
                } catch (Throwable e) {
                    throw new RuntimeException("System failed at slot " + slot, e);
                }

                for (int i = 0; i < paramCount; i++) {
                    if (isWrite[i]) {
                        var m = localMuts[i];
                        ((ComponentStorage) localStorages[i]).set(m.slot(), m.flush());
                    }
                }
            }
        }
    }
}
