package zzuegg.ecs.relation;

import zzuegg.ecs.entity.Entity;

import java.util.Arrays;

/**
 * Small-map of {@code target Entity → payload} for one source entity
 * in a non-fragmenting relation store. Backed by two parallel flat
 * arrays — {@code long[] targetIds} (Entity ids) and {@code Object[]
 * values} — with linear-scan lookup. This is faster than
 * {@link java.util.HashMap} for the typical "1–10 pairs per entity"
 * workloads the relation feature is designed for:
 *
 * <ul>
 *   <li><b>Lookup:</b> one tight array walk. No Node-chain pointer
 *       chasing, no hash computation, no Entity.equals call.</li>
 *   <li><b>Iteration:</b> a plain indexed for-loop over {@code size}
 *       contiguous slots. The JIT can unroll it and the memory
 *       access pattern is sequential. No
 *       {@code HashMap$HashIterator} allocation, no {@code Node.next}
 *       walk through a sparse 16-slot table holding one element.</li>
 *   <li><b>Memory:</b> for a typical size-1 slice this is
 *       {@code 2 * 8 + 2 * 8 = 32 bytes} of payload (two 1-element
 *       arrays plus a size field) vs HashMap's 48-byte {@code Node}
 *       plus a 16-slot {@code Node[]} table (~192 bytes). About 6×
 *       smaller.</li>
 * </ul>
 *
 * <p>The trade-off is O(n) put/get/remove. That's a loss once n is
 * large — somewhere around 30–50 entries — but the relation feature
 * is explicitly for the small-n case. Users who genuinely need a
 * predator with hundreds of simultaneous hunt pairs will have to
 * accept that this class won't scale with them.
 *
 * <p>Thread-safety: none. The containing {@code RelationStore} is
 * single-writer by contract.
 */
public final class TargetSlice<T extends Record> {

    private static final int INITIAL_CAPACITY = 2;

    private long[] targetIds;
    private Object[] values;
    private int size;

    TargetSlice() {
        this.targetIds = new long[INITIAL_CAPACITY];
        this.values = new Object[INITIAL_CAPACITY];
        this.size = 0;
    }

    public int size() { return size; }

    public boolean isEmpty() { return size == 0; }

    /**
     * Current backing target-ids array. Length may exceed
     * {@link #size()}; callers must bound their iteration with
     * {@code size()}. Framework-internal — exposed as public for
     * tier-1 generated bytecode to read directly; do not mutate.
     */
    public long[] targetIdsArray() { return targetIds; }

    /** Current backing payload values array. Same contract as {@link #targetIdsArray}. */
    public Object[] valuesArray() { return values; }

    @SuppressWarnings("unchecked")
    T get(Entity target) {
        long tid = target.id();
        var ids = targetIds;
        var vals = values;
        int n = size;
        for (int i = 0; i < n; i++) {
            if (ids[i] == tid) return (T) vals[i];
        }
        return null;
    }

    /**
     * Insert or overwrite the payload for {@code target}. Returns
     * the previous payload, or {@code null} if the target was new.
     */
    @SuppressWarnings("unchecked")
    T put(Entity target, T value) {
        long tid = target.id();
        var ids = targetIds;
        var vals = values;
        int n = size;
        for (int i = 0; i < n; i++) {
            if (ids[i] == tid) {
                var old = (T) vals[i];
                vals[i] = value;
                return old;
            }
        }
        // Append — grow if needed.
        if (n == ids.length) {
            int newCap = ids.length * 2;
            targetIds = Arrays.copyOf(ids, newCap);
            values = Arrays.copyOf(vals, newCap);
            ids = targetIds;
            vals = values;
        }
        ids[n] = tid;
        vals[n] = value;
        size = n + 1;
        return null;
    }

    /**
     * Remove the entry for {@code target}. Returns the removed payload,
     * or {@code null} if the target wasn't present. Uses swap-remove
     * so ordering is not preserved.
     */
    @SuppressWarnings("unchecked")
    T remove(Entity target) {
        long tid = target.id();
        var ids = targetIds;
        var vals = values;
        int n = size;
        for (int i = 0; i < n; i++) {
            if (ids[i] == tid) {
                var old = (T) vals[i];
                int last = n - 1;
                if (i != last) {
                    ids[i] = ids[last];
                    vals[i] = vals[last];
                }
                ids[last] = 0L;
                vals[last] = null;
                size = last;
                return old;
            }
        }
        return null;
    }
}
