package zzuegg.ecs.storage;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Array;
import java.lang.reflect.RecordComponent;

/**
 * Single concrete SoA storage class for all primitive-only record types.
 *
 * <p>Unlike the per-type hidden classes generated by {@link SoAComponentStorage},
 * this class handles any record type using cached {@link MethodHandle}s for
 * field accessors and the canonical constructor. The key benefit: every SoA
 * storage instance in a {@code Chunk} is the same concrete class, so the
 * JIT sees a <b>monomorphic</b> call site at {@code storage.set/get} and can
 * inline it. With per-type hidden classes, the call site was megamorphic
 * (one hidden class per record type), preventing inlining on the mutation
 * path ({@code World.setComponent/getComponent}).
 *
 * <p>The tier-1 generated system loops are unaffected — they access the raw
 * primitive arrays via {@link #soaFieldArrays()} and never call {@code set/get}.
 */
public final class UnifiedSoAStorage<T extends Record> implements ComponentStorage<T> {

    private final Class<T> type;
    private final int capacity;
    private final Object[] fieldArrays;
    private final Object[] cachedFieldArrays;
    private final Class<?>[] fieldTypes;
    private final MethodHandle[] accessors;  // (Record) → primitive
    private final MethodHandle constructor;       // (primitives...) → Record
    private final MethodHandle constructorSpreader; // (Object[]) → Record

    @SuppressWarnings("unchecked")
    public UnifiedSoAStorage(Class<T> type, int capacity) {
        this.type = type;
        this.capacity = capacity;

        var comps = type.getRecordComponents();
        this.fieldTypes = new Class<?>[comps.length];
        this.fieldArrays = new Object[comps.length];
        this.accessors = new MethodHandle[comps.length];

        var ctorParamTypes = new Class<?>[comps.length];

        try {
            var lookup = MethodHandles.privateLookupIn(type, MethodHandles.lookup());
            for (int i = 0; i < comps.length; i++) {
                var pt = comps[i].getType();
                fieldTypes[i] = pt;
                ctorParamTypes[i] = pt;
                fieldArrays[i] = Array.newInstance(pt, capacity);
                // Adapt accessor: (ConcreteRecord) → prim  →  (Record) → prim
                accessors[i] = lookup.unreflect(comps[i].getAccessor())
                    .asType(MethodType.methodType(pt, Record.class));
            }
            // Adapt constructor: (prims...) → ConcreteRecord  →  (prims...) → Record
            this.constructor = lookup.findConstructor(type, MethodType.methodType(void.class, ctorParamTypes))
                .asType(MethodType.methodType(Record.class, ctorParamTypes));
            // Pre-compute a spreader that takes Object[] and unboxes to primitives.
            this.constructorSpreader = this.constructor.asSpreader(Object[].class, comps.length);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException("Cannot create SoA storage for " + type.getName(), e);
        }

        // Cache a copy of fieldArrays for soaFieldArrays().
        this.cachedFieldArrays = fieldArrays.clone();
    }

    @Override
    @SuppressWarnings("unchecked")
    public T get(int slot) {
        try {
            var args = new Object[fieldTypes.length];
            for (int f = 0; f < fieldTypes.length; f++) {
                args[f] = loadField(f, slot);
            }
            return (T) (Record) constructorSpreader.invokeExact(args);
        } catch (Throwable t) {
            throw new RuntimeException("SoA get failed for " + type.getName(), t);
        }
    }

    @Override
    public void set(int slot, T value) {
        for (int f = 0; f < fieldTypes.length; f++) {
            storeField(f, slot, value);
        }
    }

    @Override
    public void swapRemove(int index, int count) {
        int last = count - 1;
        if (index >= last) return;
        for (int f = 0; f < fieldTypes.length; f++) {
            swapField(f, index, last);
        }
    }

    @Override
    public void copyInto(int srcIndex, ComponentStorage<T> dst, int dstIndex) {
        dst.set(dstIndex, get(srcIndex));
    }

    @Override
    public int capacity() {
        return capacity;
    }

    @Override
    public Class<T> type() {
        return type;
    }

    @Override
    public Object[] soaFieldArrays() {
        return cachedFieldArrays;
    }

    // --- field-level primitive operations ---

    private Object loadField(int f, int slot) {
        var t = fieldTypes[f];
        if (t == float.class) return ((float[]) fieldArrays[f])[slot];
        if (t == int.class) return ((int[]) fieldArrays[f])[slot];
        if (t == double.class) return ((double[]) fieldArrays[f])[slot];
        if (t == long.class) return ((long[]) fieldArrays[f])[slot];
        if (t == boolean.class) return ((boolean[]) fieldArrays[f])[slot];
        if (t == byte.class) return ((byte[]) fieldArrays[f])[slot];
        if (t == short.class) return ((short[]) fieldArrays[f])[slot];
        if (t == char.class) return ((char[]) fieldArrays[f])[slot];
        throw new IllegalArgumentException("Not a primitive: " + t);
    }

    private void storeField(int f, int slot, Record value) {
        try {
            var t = fieldTypes[f];
            if (t == float.class) {
                ((float[]) fieldArrays[f])[slot] = (float) accessors[f].invokeExact(value);
            } else if (t == int.class) {
                ((int[]) fieldArrays[f])[slot] = (int) accessors[f].invokeExact(value);
            } else if (t == double.class) {
                ((double[]) fieldArrays[f])[slot] = (double) accessors[f].invokeExact(value);
            } else if (t == long.class) {
                ((long[]) fieldArrays[f])[slot] = (long) accessors[f].invokeExact(value);
            } else if (t == boolean.class) {
                ((boolean[]) fieldArrays[f])[slot] = (boolean) accessors[f].invokeExact(value);
            } else if (t == byte.class) {
                ((byte[]) fieldArrays[f])[slot] = (byte) accessors[f].invokeExact(value);
            } else if (t == short.class) {
                ((short[]) fieldArrays[f])[slot] = (short) accessors[f].invokeExact(value);
            } else if (t == char.class) {
                ((char[]) fieldArrays[f])[slot] = (char) accessors[f].invokeExact(value);
            }
        } catch (Throwable t) {
            throw new RuntimeException("SoA store failed", t);
        }
    }

    private void swapField(int f, int dst, int src) {
        var t = fieldTypes[f];
        if (t == float.class) { var a = (float[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == int.class) { var a = (int[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == double.class) { var a = (double[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == long.class) { var a = (long[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == boolean.class) { var a = (boolean[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == byte.class) { var a = (byte[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == short.class) { var a = (short[]) fieldArrays[f]; a[dst] = a[src]; }
        else if (t == char.class) { var a = (char[]) fieldArrays[f]; a[dst] = a[src]; }
    }
}
